### PR TITLE
fix: Ensures sheet clears between pages

### LINKED ISSUE #25: [WMR]: Stylesheets not clearing between pages being prerendered
@sastan: do you happen to remember the context of this comment?

https://github.com/tw-in-js/use-twind-with/blob/d40071a0d91319d4a07ceb09b4a03e4f4d7c729d/packages/wmr/prerender.ts#L22-L24

Running into an issue at the moment where previous styles aren't cleared from the stylesheet, and for whatever reason, this seems to be the culprit.

I've made a reproduction: https://github.com/rschristian/twind-uncleared-sheet-bug

This is just the [WMR Example](https://github.com/tw-in-js/example-wmr) brought up to date and configured to also prerender a 'Not Found' page.

Once you build (`npm run build`), if you look at the built file (`dist/404/index.html`) you'll see that Twind has generated a rule for `.bg-purple-400`, even though it doesn't exist on any content in the page. It does, however, exist in `/`.

I'm not really sure what you're looking to do with that `Promise.resolve().then(...)`. Replacing that and returning a plain async function seems to fix the issue.

```diff
// Ensure to start a new async scope
-return (data) =>
-    Promise.resolve().then(async () => {
+return async (data) => {
        await sheet.reset()
        let { html, ...rest } = await prerender(render(data), options)
        return { ...rest, html: getStyleTag(sheet) + html }
-})
+}
}
```

### PR DESCRIPTION
**Pull request by rschristian**
Closes #25 

It's a bit odd, but seems to fix the issue as noted.

### CODE REVIEW

**Comment by rschristian** [comment]
@sastan Looks like a bad merge, there's a trailing `)` now

**Comment by sastan** [comment]
Thanks. Did it in the web ui.

**Comment by sastan** [comment]
Should be fixed now: https://github.com/tw-in-js/use-twind-with/commit/0f1d9b499b9e60998b19fb1f28abbb128bef2966

**Comment by rschristian** [comment]
Awesome, thanks!

**Pull request merged**
